# Generated by Django 5.1.3 on 2024-11-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voter_id", models.TextField()),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("street_num", models.TextField()),
                ("street_name", models.TextField()),
                ("apt_num", models.TextField()),
                ("zipcode", models.TextField()),
                ("dob", models.DateField()),
                ("date_of_registration", models.DateField()),
                ("party", models.CharField(max_length=3)),
                ("precinct_num", models.IntegerField()),
                ("v20state", models.BooleanField()),
                ("v21town", models.BooleanField()),
                ("v21primary", models.BooleanField()),
                ("v22general", models.BooleanField()),
                ("v23town", models.BooleanField()),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
