# Generated by Django 5.1.3 on 2024-11-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="contact_info",
            field=models.TextField(default="contact_info"),
        ),
        migrations.AddField(
            model_name="developer",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="developer",
            name="location",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="image",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="review",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reviewer",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reviewer",
            name="profile_img",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="reviewer",
            name="username",
            field=models.TextField(default="reviewer"),
        ),
        migrations.AddField(
            model_name="videogame",
            name="date_released",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videogame",
            name="genre",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="videogame",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
