# Generated by Django 5.1.3 on 2024-11-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "game_review",
            "0003_remove_image_game_remove_image_review_gameimage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="profile_img",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="videogame",
            name="main_image",
            field=models.ImageField(default=2, upload_to=""),
            preserve_default=False,
        ),
    ]
