# Generated by Django 5.1.3 on 2024-11-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_review", "0004_developer_profile_img_videogame_main_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="video_game",
            new_name="game",
        ),
        migrations.AddField(
            model_name="videogame",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
