# Generated by Django 5.1.3 on 2024-11-26 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game_review", "0006_reviewer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewer",
            name="user",
        ),
    ]
