# Generated by Django 5.1.3 on 2024-11-29 05:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game_review", "0008_reviewer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videogame",
            name="rating",
        ),
    ]
