# Generated by Django 5.1.1 on 2024-10-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_fb", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="email",
            new_name="email_address",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="image_url",
            new_name="profile_image_url",
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.TextField(default="Some Place"),
        ),
    ]
